name: Deploy SocialEvent Frontend

# Triggers the workflow on any push to the addnewFeature branch or pull request
on:
  push:
    branches: [ addnewFeature ]
    paths:
      - 'Client/**'

# job (groups of task run on same runner(machine))
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest #Container where entire application runs and test

    steps:
    # step1: checkout the code frrom the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup nodejs environment
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: Client/package-lock.json

    - name: Install Dependencies
      working-directory: Client
      run: |
        npm install
        npm install -D esbuild

    - name: Build Web Production Assets
      working-directory: Client
      run: npx vite build
      env:
        VITE_BACKEND_URL: ${{ secrets.PRODUCTION_BACKEND_URL }}
        VITE_WS_URL: ${{ secrets.PRODUCTION_WS_URL }}
        CI: false

    - name: Trigger Static Content Update
      run: curl -X POST "${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}"