name: Deploy SocialEvent Frontend

on:
  push:
    branches:
      - devopsFeature
    paths:
      - "Client/**"

  pull_request:
    branches:
      - devopsFeature
    paths:
      - "Client/**"


jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Build Docker Image
        run: |
          docker build \
          --build-arg VITE_GRAPHQL_URL=${{ secrets.PRODUCTION_GRAPHQL_URL }} \
          --build-arg VITE_WS_URL=${{ secrets.PRODUCTION_WS_URL }} \
          -t socialevent-frontend \
          ./Client


      - name: Trigger Render Deployment
        if: github.event_name == 'push'
        run: |
          curl -X POST "${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}"